import Link from "next/link"

export const metadata = { title: "Privacy Policy — Conduct" }

export default function PrivacyPage() {
  return (
    <div className="min-h-screen bg-stone-50">
      <div className="max-w-2xl mx-auto px-6 py-16">
        <Link href="/" className="text-xs text-stone-400 hover:text-stone-700 transition-colors mb-8 inline-block">← Back to Conduct</Link>
        <h1 className="text-2xl font-bold text-stone-900 mb-2">Privacy Policy</h1>
        <p className="text-xs text-stone-400 mb-10">Last updated: May 2025</p>
        <div className="prose prose-stone prose-sm max-w-none space-y-6 text-stone-600 leading-relaxed">
          <section>
            <h2 className="text-base font-semibold text-stone-800 mb-2">What we collect</h2>
            <p>We collect the minimum information needed to run the service: your email address (via Clerk authentication), workflow configurations you create, and run logs generated by your agents. We do not sell your data.</p>
          </section>
          <section>
            <h2 className="text-base font-semibold text-stone-800 mb-2">Credentials and secrets</h2>
            <p>API keys and tokens you store in Conduct are encrypted at rest using AES-256. They are decrypted only at runtime to execute your agent workflows and are never logged or exposed in plaintext.</p>
          </section>
          <section>
            <h2 className="text-base font-semibold text-stone-800 mb-2">Third-party services</h2>
            <p>Conduct integrates with GitHub, Slack, and other services on your behalf. We access only the scopes you explicitly authorize. We do not store OAuth tokens beyond what is required to operate your workflows.</p>
          </section>
          <section>
            <h2 className="text-base font-semibold text-stone-800 mb-2">Data retention</h2>
            <p>Run logs are retained for 90 days by default. You can delete your workspace and all associated data at any time from Settings.</p>
          </section>
          <section>
            <h2 className="text-base font-semibold text-stone-800 mb-2">Contact</h2>
            <p>Questions? Email us at <a href="mailto:hello@conductagentic.com" className="text-stone-900 underline hover:no-underline">hello@conductagentic.com</a>.</p>
          </section>
        </div>
      </div>
    </div>
  )
}
