"""
POST /sdd/generate — unauthenticated spec generation (free public tool)

Rate-limited by IP: 5 requests per day using in-process counter (restarts on
deploy, good enough for a public tool at this scale). No workspace or auth
required — uses the platform Anthropic key from settings.
"""
import time
import structlog
from collections import defaultdict
from fastapi import APIRouter, HTTPException, Request
from pydantic import BaseModel

from app.core.config import settings
from app.runtime.llm_client import AnthropicClient, LLMTextBlock

log = structlog.get_logger(__name__)
router = APIRouter(prefix="/sdd", tags=["sdd"])

# In-process rate limit store: ip → list of timestamps
_rate_store: dict[str, list[float]] = defaultdict(list)
_RATE_LIMIT = 5       # requests per window
_RATE_WINDOW = 86400  # 24 hours in seconds

SYSTEM_PROMPT = """\
You are a Spec-Driven Development (SDD) assistant. Your job is to produce a
high-quality SPEC.md file from a project description and clarifying answers.

Rules for every FR you write:
- Atomic: one behaviour per requirement
- Testable: includes a clear acceptance criterion
- Traceable: written so a PR can reference it unambiguously
- Non-implementation-specific: describes WHAT, not HOW

Output ONLY the raw SPEC.md content — no preamble, no code fences, no
explanation. Start with the # heading. The file will be committed directly.

SPEC.md structure:
# <Project Name> Spec · v1.0
Generated by Conduct SDD · <today's date>

## Project Overview
<2-3 sentence summary>

## User Personas
<bulleted list>

## Functional Requirements
**FR-001** <requirement title>
  _Acceptance: <one-line pass/fail criterion>_

**FR-002** ...

## Non-Functional Requirements
**NFR-001** ...

## Out of Scope
<bulleted list>

## Open Questions
❓ <flag any FRs that need more clarity — if none, omit this section>
"""


def _check_rate_limit(ip: str) -> None:
    now = time.time()
    window_start = now - _RATE_WINDOW
    timestamps = [t for t in _rate_store[ip] if t > window_start]
    _rate_store[ip] = timestamps
    if len(timestamps) >= _RATE_LIMIT:
        raise HTTPException(
            status_code=429,
            detail=f"Rate limit reached — {_RATE_LIMIT} free specs per day. Sign in to Conduct for unlimited access.",
        )
    _rate_store[ip].append(now)


class GenerateRequest(BaseModel):
    description: str
    source_url: str | None = None
    answers: dict[str, str] = {}  # users, out_of_scope, constraints


class GenerateResponse(BaseModel):
    spec: str


@router.post("/generate", response_model=GenerateResponse)
def generate_spec(req: GenerateRequest, request: Request) -> GenerateResponse:
    ip = request.client.host if request.client else "unknown"
    _check_rate_limit(ip)

    if not settings.anthropic_api_key:
        raise HTTPException(status_code=503, detail="Spec generation not available — platform key not configured.")

    if not req.description.strip():
        raise HTTPException(status_code=422, detail="Description is required.")

    users = req.answers.get("users", "").strip()
    out_of_scope = req.answers.get("out_of_scope", "").strip()
    constraints = req.answers.get("constraints", "").strip()

    user_prompt = f"""Project description:
{req.description.strip()}
"""
    if req.source_url:
        user_prompt += f"\nSource document URL: {req.source_url}\n"
    if users:
        user_prompt += f"\nPrimary users and their goal: {users}\n"
    if out_of_scope:
        user_prompt += f"\nExplicitly out of scope: {out_of_scope}\n"
    if constraints:
        user_prompt += f"\nHard constraints (tech stack, compliance, timeline): {constraints}\n"

    user_prompt += "\nWrite the complete SPEC.md now."

    try:
        client = AnthropicClient(api_key=settings.anthropic_api_key)
        result = client.create(
            model="claude-haiku-4-5-20251001",
            system=SYSTEM_PROMPT,
            messages=[{"role": "user", "content": user_prompt}],
            max_tokens=4096,
        )
    except Exception as exc:
        log.error("sdd.generate_failed", error=str(exc), ip=ip)
        raise HTTPException(status_code=500, detail="Spec generation failed — please try again.")

    spec_text = "".join(
        block.text for block in result.content if isinstance(block, LLMTextBlock)
    ).strip()

    if not spec_text:
        raise HTTPException(status_code=500, detail="Generation returned empty response.")

    log.info("sdd.spec_generated", ip=ip, description_len=len(req.description))
    return GenerateResponse(spec=spec_text)
