"""
POST /sdd/generate — unauthenticated spec generation (free public tool)

Rate-limited by IP: 5 requests per day using in-process counter (restarts on
deploy, good enough for a public tool at this scale). No workspace or auth
required — uses the platform Anthropic key from settings.
"""
import time
import datetime
import structlog
from collections import defaultdict
from fastapi import APIRouter, HTTPException, Request
from fastapi.responses import StreamingResponse
from pydantic import BaseModel

from app.core.config import settings
from app.runtime.llm_client import AnthropicClient, LLMTextBlock

log = structlog.get_logger(__name__)
router = APIRouter(prefix="/sdd", tags=["sdd"])

# In-process rate limit store: ip → list of timestamps
_rate_store: dict[str, list[float]] = defaultdict(list)
_RATE_LIMIT = 5       # requests per window
_RATE_WINDOW = 86400  # 24 hours in seconds

SYSTEM_PROMPT = """\
You are a Spec-Driven Development (SDD) assistant. Your job is to produce a
high-quality SPEC.md file from a project description and clarifying answers.

Rules for every FR you write:
- Atomic: one behaviour per requirement
- Testable: includes a clear acceptance criterion
- Traceable: written so a PR can reference it unambiguously
- Non-implementation-specific: describes WHAT, not HOW

Output ONLY the raw SPEC.md content — no preamble, no code fences, no
explanation. Start with the # heading. The file will be committed directly.

SPEC.md structure:
# <Project Name> Spec · v1.0
Generated by Conduct SDD · <today's date>

## Project Overview
<2-3 sentence summary>

## User Personas
<bulleted list>

## Functional Requirements
**FR-001** <requirement title>
  _Acceptance: <one-line pass/fail criterion>_

**FR-002** ...

## Non-Functional Requirements
**NFR-001** ...

## Out of Scope
<bulleted list>

## Open Questions
❓ <flag any FRs that need more clarity — if none, omit this section>
"""


def _check_rate_limit(ip: str) -> None:
    now = time.time()
    window_start = now - _RATE_WINDOW
    timestamps = [t for t in _rate_store[ip] if t > window_start]
    _rate_store[ip] = timestamps
    if len(timestamps) >= _RATE_LIMIT:
        raise HTTPException(
            status_code=429,
            detail=f"Rate limit reached — {_RATE_LIMIT} free specs per day. Sign in to Conduct for unlimited access.",
        )
    _rate_store[ip].append(now)


QUESTIONS_SYSTEM_PROMPT = """\
You are a Spec-Driven Development (SDD) assistant. Given a project description, generate
exactly 3 clarifying questions that are SPECIFIC to what was described — not generic.

Rules:
- Read the description carefully. Ask only about gaps that actually exist in THIS description.
- Never ask generic questions like "who are the users?" if the description already names them.
- Questions must be concrete: "Does this need PCI-DSS compliance?" beats "Any compliance needs?"
- Each question must be answerable in 1-2 sentences.

Examples of good context-specific questions:
- Payments product: "Does checkout need PCI-DSS compliance, or will you use a processor like Stripe that handles it?"
- Mobile app: "iOS only, Android only, or cross-platform (React Native / Flutter)?"
- AI tool: "Which LLM providers must be supported at launch, and is there a monthly token cost budget?"
- B2B SaaS: "Is SSO / SAML required for enterprise customers at launch?"
- Data pipeline: "What's the expected data volume and acceptable latency — near-real-time or batch?"

Output ONLY a raw JSON array — no markdown fences, no explanation:
[
  {"key": "constraints", "question": "<specific question 1>"},
  {"key": "users", "question": "<specific question 2>"},
  {"key": "out_of_scope", "question": "<specific question 3>"}
]

Keys must be one of: users, out_of_scope, constraints, auth, data_model, integrations, scale.
"""


class QuestionsRequest(BaseModel):
    description: str


class Question(BaseModel):
    key: str
    question: str


class QuestionsResponse(BaseModel):
    questions: list[Question]


class GenerateRequest(BaseModel):
    description: str
    source_url: str | None = None
    answers: dict[str, str] = {}  # users, out_of_scope, constraints


class GenerateResponse(BaseModel):
    spec: str


@router.post("/questions", response_model=QuestionsResponse)
def get_questions(req: QuestionsRequest, request: Request) -> QuestionsResponse:
    ip = request.client.host if request.client else "unknown"
    _check_rate_limit(ip)

    if not settings.anthropic_api_key:
        raise HTTPException(status_code=503, detail="Not available — platform key not configured.")

    if not req.description.strip():
        raise HTTPException(status_code=422, detail="Description is required.")

    try:
        import json as _json
        client = AnthropicClient(api_key=settings.anthropic_api_key)
        result = client.create(
            model="claude-sonnet-4-6",
            system=QUESTIONS_SYSTEM_PROMPT,
            messages=[{"role": "user", "content": req.description.strip()}],
            max_tokens=512,
        )
        raw = "".join(
            block.text for block in result.content if isinstance(block, LLMTextBlock)
        ).strip()
        # Strip markdown code fences if Sonnet wraps the JSON
        if raw.startswith("```"):
            raw = raw.split("```")[1]
            if raw.startswith("json"):
                raw = raw[4:]
        questions = [Question(**q) for q in _json.loads(raw.strip())]
    except Exception as exc:
        log.warning("sdd.questions_failed", error=str(exc), ip=ip)
        # Fall back to generic questions on any failure
        questions = [
            Question(key="users", question="Who are the primary users? What's their main goal?"),
            Question(key="out_of_scope", question="What's explicitly out of scope for this version?"),
            Question(key="constraints", question="Any hard constraints? (tech stack, compliance, timeline)"),
        ]

    return QuestionsResponse(questions=questions)


@router.post("/generate", response_model=GenerateResponse)
def generate_spec(req: GenerateRequest, request: Request) -> GenerateResponse:
    ip = request.client.host if request.client else "unknown"
    _check_rate_limit(ip)

    if not settings.anthropic_api_key:
        raise HTTPException(status_code=503, detail="Spec generation not available — platform key not configured.")

    if not req.description.strip():
        raise HTTPException(status_code=422, detail="Description is required.")

    users = req.answers.get("users", "").strip()
    out_of_scope = req.answers.get("out_of_scope", "").strip()
    constraints = req.answers.get("constraints", "").strip()

    user_prompt = f"""Project description:
{req.description.strip()}
"""
    if req.source_url:
        user_prompt += f"\nSource document URL: {req.source_url}\n"
    if users:
        user_prompt += f"\nPrimary users and their goal: {users}\n"
    if out_of_scope:
        user_prompt += f"\nExplicitly out of scope: {out_of_scope}\n"
    if constraints:
        user_prompt += f"\nHard constraints (tech stack, compliance, timeline): {constraints}\n"

    today = datetime.date.today().strftime("%Y-%m-%d")
    user_prompt += f"\nToday's date is {today}. Use it in the 'Generated by Conduct SDD · <date>' line.\n"
    user_prompt += "\nWrite the complete SPEC.md now."

    try:
        client = AnthropicClient(api_key=settings.anthropic_api_key)
        result = client.create(
            model="claude-sonnet-4-6",
            system=SYSTEM_PROMPT,
            messages=[{"role": "user", "content": user_prompt}],
            max_tokens=4096,
        )
    except Exception as exc:
        log.error("sdd.generate_failed", error=str(exc), ip=ip)
        raise HTTPException(status_code=500, detail="Spec generation failed — please try again.")

    spec_text = "".join(
        block.text for block in result.content if isinstance(block, LLMTextBlock)
    ).strip()

    if not spec_text:
        raise HTTPException(status_code=500, detail="Generation returned empty response.")

    log.info("sdd.spec_generated", ip=ip, description_len=len(req.description))
    return GenerateResponse(spec=spec_text)


# ── Scaffold ───────────────────────────────────────────────────────────────

_SCAFFOLD_PROMPTS: dict[str, str] = {
    "AGENTS.md": """\
You are an SDD scaffold generator. Given a SPEC.md, write AGENTS.md.

AGENTS.md instructs AI coding agents (Claude Code, Copilot, Cursor, etc.) on how to
work within this project's spec. Format:

# AGENTS.md

## Project Spec
One sentence referencing SPEC.md as the source of truth.

## Requirement References
Every commit, PR, and comment MUST reference at least one FR-xxx from SPEC.md.

## Agent Rules
Bullet list of project-specific rules derived from the spec (tech constraints,
out-of-scope boundaries, security requirements, etc.)

## FR Quick Reference
Table: | FR | Title | Status |
List every FR from the spec with status = open.

Output raw markdown only. No preamble.""",

    "DESIGN.md": """\
You are an SDD scaffold generator. Given a SPEC.md, write DESIGN.md.

DESIGN.md captures architecture decisions required to satisfy the FRs. Format:

# DESIGN.md

## Architecture Overview
2-3 sentence summary of the system shape.

## Component Map
Table or list of major components and their responsibility.

## Key Design Decisions
For each significant decision: **Decision**, Rationale, Alternatives considered.
Ground each decision in the FR(s) that drove it.

## Data Model Sketch
Key entities and relationships (prose or simple table — no SQL).

## Integration Points
External services, APIs, or platforms referenced in the spec.

Output raw markdown only. No preamble.""",

    "PLAN.md": """\
You are an SDD scaffold generator. Given a SPEC.md, write PLAN.md.

PLAN.md is a phased implementation plan ordered by dependency and risk. Format:

# PLAN.md

## Phase 1 — Foundation
FRs to implement first (infrastructure, auth, core data model). List each FR with
a one-line implementation note.

## Phase 2 — Core Features
FRs that deliver the primary user value.

## Phase 3 — Polish & NFRs
Remaining FRs, NFRs, integrations, observability.

## Dependencies
Any cross-FR dependencies or sequencing constraints.

Output raw markdown only. No preamble.""",

    "SPRINT.md": """\
You are an SDD scaffold generator. Given a SPEC.md, write SPRINT.md for Sprint 1.

SPRINT.md is the sprint 1 scope — the smallest slice that delivers a working system.
Pick the ~20% of FRs that unlock everything else. Format:

# SPRINT.md — Sprint 1

## Goal
One sentence: what a developer can do at the end of this sprint.

## In Scope
| FR | Title | Acceptance shorthand |
List only the FRs included in sprint 1.

## Out of Sprint 1
Brief list of deferred FRs and why.

## Definition of Done
Bulleted checklist.

Output raw markdown only. No preamble.""",

    "CLAUDE.md": """\
You are an SDD scaffold generator. Given a SPEC.md, write CLAUDE.md for this project.

CLAUDE.md gives Claude Code project-specific context and rules. Format:

# CLAUDE.md

## About This Project
One paragraph summary of what the project does.

## Spec Reference
All work must reference FR-xxx from SPEC.md. Link: ./SPEC.md

## Tech Stack
List the stack implied by the spec (or marked as TBD if unspecified).

## Key Rules
Project-specific rules Claude must follow (security constraints, out-of-scope
items, naming conventions implied by the spec, etc.)

## Commands
Placeholder section for build/test/lint commands (fill in after scaffolding).

Output raw markdown only. No preamble.""",
}


def _parse_spec_index(spec: str) -> list[dict]:
    import re
    frs = []
    for m in re.finditer(r'\*\*FR-(\d+)\*\*\s+(.+?)(?:\n|$)', spec):
        frs.append({"id": f"FR-{m.group(1)}", "title": m.group(2).strip(), "status": "open"})
    return frs


class ScaffoldRequest(BaseModel):
    spec: str


class ScaffoldFile(BaseModel):
    name: str
    content: str


class ScaffoldResponse(BaseModel):
    files: list[ScaffoldFile]


@router.post("/scaffold", response_model=ScaffoldResponse)
def scaffold_repo(req: ScaffoldRequest, request: Request) -> ScaffoldResponse:
    ip = request.client.host if request.client else "unknown"
    _check_rate_limit(ip)

    if not settings.anthropic_api_key:
        raise HTTPException(status_code=503, detail="Scaffold generation not available — platform key not configured.")

    if not req.spec.strip():
        raise HTTPException(status_code=422, detail="Spec is required.")

    client = AnthropicClient(api_key=settings.anthropic_api_key)
    files: list[ScaffoldFile] = []

    for filename, system in _SCAFFOLD_PROMPTS.items():
        try:
            result = client.create(
                model="claude-sonnet-4-6",
                system=system,
                messages=[{"role": "user", "content": req.spec}],
                max_tokens=2048,
            )
            content = "".join(
                block.text for block in result.content if isinstance(block, LLMTextBlock)
            ).strip()
            files.append(ScaffoldFile(name=filename, content=content))
        except Exception as exc:
            log.warning("sdd.scaffold_file_failed", file=filename, error=str(exc))
            files.append(ScaffoldFile(name=filename, content=f"# {filename}\n\nGeneration failed — please retry."))

    # spec-index.json is deterministic — no LLM needed
    import json as _json
    spec_index = _parse_spec_index(req.spec)
    files.append(ScaffoldFile(name="spec-index.json", content=_json.dumps(spec_index, indent=2)))

    log.info("sdd.scaffold_generated", ip=ip, files=len(files))
    return ScaffoldResponse(files=files)


@router.post("/scaffold/stream")
def scaffold_stream(req: ScaffoldRequest, request: Request) -> StreamingResponse:
    ip = request.client.host if request.client else "unknown"
    _check_rate_limit(ip)

    if not settings.anthropic_api_key:
        raise HTTPException(status_code=503, detail="Scaffold generation not available — platform key not configured.")

    if not req.spec.strip():
        raise HTTPException(status_code=422, detail="Spec is required.")

    def generate():
        import json as _json

        # spec-index.json first — deterministic, instant
        spec_index = _parse_spec_index(req.spec)
        yield _json.dumps({"name": "spec-index.json", "content": _json.dumps(spec_index, indent=2)}) + "\n"

        client = AnthropicClient(api_key=settings.anthropic_api_key)
        for filename, system in _SCAFFOLD_PROMPTS.items():
            try:
                result = client.create(
                    model="claude-sonnet-4-6",
                    system=system,
                    messages=[{"role": "user", "content": req.spec}],
                    max_tokens=2048,
                )
                content = "".join(
                    block.text for block in result.content if isinstance(block, LLMTextBlock)
                ).strip()
            except Exception as exc:
                log.warning("sdd.scaffold_stream_file_failed", file=filename, error=str(exc))
                content = f"# {filename}\n\nGeneration failed — please retry."
            yield _json.dumps({"name": filename, "content": content}) + "\n"

        log.info("sdd.scaffold_streamed", ip=ip)

    return StreamingResponse(generate(), media_type="application/x-ndjson")
