export const TOOLS = [
  {
    id: "conduct",
    shortName: "Conduct",
    name: "Conduct AI",
    maker: "Conduct",
    emoji: "🎯",
    category: "Orchestration",
    categoryColor: "bg-indigo-100 text-indigo-700",
    url: "https://conductai.ai",
    oneLiner: "Governed AI automations for engineering teams — turn tickets, PRs, alerts, and incidents into auditable agent workflows.",
    description: "Conduct is a governed automation layer for engineering teams. It doesn't replace GitHub, Git, or your IDE — it wraps around your existing stack to automate the repetitive parts: reviewing PRs, fixing labeled issues, triaging incoming bugs, diagnosing CI failures, patching dependencies, and responding to incidents. Every automation is a visual YAML playbook your team can read, fork, and customise. Human-in-the-loop approval gates are first-class blocks — nothing ships without a reviewer unless you explicitly remove the gate. Every run is fully audited with cost visibility. MIT licensed.",
    strengths: [
      "Visual canvas — see and edit the entire agent workflow at a glance",
      "Copilot↔autopilot spectrum — tune automation level per workflow",
      "Human-in-the-loop approval gates as first-class blocks",
      "Growing library of pre-built playbooks installable in one click",
      "Full autonomous fix loop: PR review → issue → autopilot → new PR",
      "Per-run cost and audit trail visibility",
      "Multi-model per block — mix Claude, GPT-4, Gemini in one workflow",
      "MIT licensed, config-as-code, no vendor lock-in",
      "Works across verticals — not just SDLC",
    ],
    tradeoffs: [
      "Early-stage product — some rough edges and missing integrations",
      "Sandbox execution requires configuring a workspace runtime such as Modal or SSH",
      "Smaller community than GitHub Copilot or Amazon Q",
      "No IDE extension — purely web canvas + CLI",
      "Self-hosted option not yet available",
    ],
    bestFor: "Engineering teams (2–20 people) using tools like GitHub, Slack, Jira, Linear, and Sentry who want AI automation around the work, not a replacement for their development workflow. Teams that want to see the agent logic, own the playbook, and put a human in the loop before anything ships.",
  },
  {
    id: "copilot",
    shortName: "Copilot",
    name: "GitHub Copilot",
    maker: "GitHub / Microsoft",
    emoji: "🐙",
    category: "AI Coding",
    categoryColor: "bg-stone-100 text-stone-700",
    url: "https://github.com/features/copilot",
    oneLiner: "AI pair programmer embedded in your IDE. Code completions, chat, and agentic PR creation via GitHub workflows.",
    description: "GitHub Copilot is the most widely adopted AI coding assistant, with 15M+ users. It works as an IDE extension (VS Code, JetBrains, Neovim) providing inline code completions, multi-file edits, and a chat interface. In 2024–2025 GitHub added agentic capabilities: Copilot can now be assigned GitHub issues, create branches, write code, and open PRs — all triggered from the GitHub web UI. The underlying model has expanded to include GPT-4o and Claude Sonnet. For teams already on GitHub Enterprise, it integrates natively with zero friction.",
    strengths: [
      "Best-in-class IDE integration — completions feel native",
      "15M+ users — widest community, tutorials, and enterprise adoption",
      "Native to GitHub — no new tool to onboard",
      "Workspace context — reads your whole repo for relevant suggestions",
      "Enterprise security and compliance (SOC 2, GDPR)",
      "Agentic issue → PR workflow available in GitHub UI",
    ],
    tradeoffs: [
      "Primarily a suggestion tool — the developer still drives",
      "Agentic workflows are limited and not visually configurable",
      "No approval gates or human-in-the-loop controls",
      "No audit trail for what the AI did across runs",
      "Closed source — cannot customise the review or automation logic",
      "Subscription cost adds up for large teams ($19–39/user/month)",
    ],
    bestFor: "Individual developers and teams who want the best autocomplete and code chat experience inside their IDE, with light agentic capabilities tied to GitHub issues. If the primary use case is writing code faster, Copilot is hard to beat.",
  },
  {
    id: "devin",
    shortName: "Devin",
    name: "Devin",
    maker: "Cognition AI",
    emoji: "🤖",
    category: "Autonomous Agent",
    categoryColor: "bg-purple-100 text-purple-700",
    url: "https://cognition.ai",
    oneLiner: "Fully autonomous AI software engineer. Give it a task; it plans, codes, tests, and deploys end-to-end in its own cloud sandbox.",
    description: "Devin is designed to be a fully autonomous software engineer — not a copilot. You give it a task in natural language and it independently: explores the codebase, creates a plan, writes code across multiple files, runs tests, debugs failures, and opens a pull request. It runs in its own isolated cloud environment with a browser, terminal, and editor. Devin is best described as a \"junior engineer\" you can hand full tasks to. It is the most capable fully-autonomous agent publicly available, and is priced accordingly for teams that need end-to-end task execution without hand-holding.",
    strengths: [
      "Most capable end-to-end autonomous coding agent available",
      "Full environment (browser, terminal, editor) — no constraints",
      "Long-horizon task execution — can work through complex, multi-step problems",
      "Handles real repos, not just toy examples",
      "Communicates progress and asks clarifying questions",
    ],
    tradeoffs: [
      "Expensive — priced for enterprise and power users",
      "Black box — limited visibility into what the agent is doing step-by-step",
      "No visual workflow editor — you describe tasks in natural language only",
      "No playbook marketplace or pre-built agent library",
      "Autonomy without guardrails can be risky on production repos",
      "No multi-agent orchestration or approval gate primitives",
    ],
    bestFor: "Teams with complex, long-horizon engineering tasks where they want to hand off an entire problem and let the agent run. Best suited for greenfield work, prototyping, or well-scoped tickets where full autonomy is safe.",
  },
  {
    id: "linearb",
    shortName: "LinearB",
    name: "LinearB",
    maker: "LinearB",
    emoji: "📊",
    category: "Eng Metrics + AI",
    categoryColor: "bg-blue-100 text-blue-700",
    url: "https://linearb.io",
    oneLiner: "Engineering metrics platform with AI-powered PR automation (gitStream) and DORA/SPACE dashboards for engineering leaders.",
    description: "LinearB combines engineering intelligence (cycle time, deployment frequency, DORA metrics) with PR automation via its gitStream product. gitStream is a YAML-based automation engine that routes PRs, enforces review policies, assigns reviewers, and auto-merges safe changes. LinearB's AI layer adds code review suggestions and automated checks. It is primarily a tool for engineering managers who want visibility into team performance alongside automated PR governance. The metrics dashboards are among the best in the market for understanding eng team health.",
    strengths: [
      "Best-in-class engineering metrics — DORA, SPACE, cycle time, review time",
      "gitStream is a powerful, mature PR automation engine",
      "Executive-friendly dashboards and reporting",
      "Strong workflow automation for review routing and policy enforcement",
      "Integrates with Jira, Linear, GitHub, GitLab, Bitbucket",
    ],
    tradeoffs: [
      "Metrics-first product — AI automation is secondary to analytics",
      "No visual canvas or workflow builder",
      "Limited agentic capabilities — PR automation, not full task execution",
      "No issue-to-PR autopilot loop",
      "Pricing scales with team size and can be expensive at scale",
    ],
    bestFor: "Engineering leaders and managers who need visibility into team performance and want policy-based PR automation. Teams that already care about DORA metrics and want automation to enforce their review process.",
  },
  {
    id: "bito",
    shortName: "Bito AI",
    name: "Bito AI",
    maker: "Bito",
    emoji: "🧩",
    category: "AI Code Review",
    categoryColor: "bg-teal-100 text-teal-700",
    url: "https://bito.ai",
    oneLiner: "AI code review bot with deep codebase awareness, Jira integration, and implementation planning — focused on architectural context.",
    description: "Bito specialises in AI-powered code review with a strong emphasis on codebase context. Unlike tools that look at just the diff, Bito indexes your entire codebase and uses that context when reviewing PRs — catching issues that require understanding of how the changed code interacts with the broader system. It also integrates with Jira to read linked tickets and provide more relevant review comments. Bito offers an IDE plugin for real-time feedback and a CLI for CI integration.",
    strengths: [
      "Deep codebase awareness — reads your full repo, not just the diff",
      "Jira integration — uses linked tickets for review context",
      "IDE plugin for real-time feedback during development",
      "Strong at architectural and cross-file impact analysis",
      "CLI for easy CI/CD integration",
    ],
    tradeoffs: [
      "Review only — no autonomous task execution or autopilot mode",
      "No visual workflow builder or playbook system",
      "No human-in-the-loop approval gates",
      "Smaller community and ecosystem than GitHub Copilot",
      "No Slack-native output or incident response features",
    ],
    bestFor: "Teams that want the most context-aware AI code reviews and are willing to trade breadth of automation for depth of review quality. Particularly strong for larger codebases where cross-file impact matters.",
  },
  {
    id: "amazonq",
    shortName: "Amazon Q",
    name: "Amazon Q Developer",
    maker: "AWS",
    emoji: "☁️",
    category: "AI Coding + Cloud",
    categoryColor: "bg-orange-100 text-orange-700",
    url: "https://aws.amazon.com/q/developer",
    oneLiner: "AWS's AI developer tool — code generation, security scanning, Java upgrades, and CI/CD automation within the AWS ecosystem.",
    description: "Amazon Q Developer is AWS's answer to GitHub Copilot, with a stronger focus on AWS infrastructure and cloud-native development. Beyond code completions, it offers unique features: automated Java version upgrades, security vulnerability scanning, and agentic software development tasks. It integrates deeply with AWS services (CodeCatalyst, CodePipeline, CloudWatch) and is the strongest choice for teams heavily invested in the AWS ecosystem. It is available free on a basic tier and included in AWS Builder ID.",
    strengths: [
      "Deep AWS integration — understands CloudFormation, CDK, Lambda natively",
      "Automated language upgrades (Java 8→17, etc.) — a unique capability",
      "Security scanning built-in — OWASP, CVE detection",
      "Free tier available — accessible to individual developers",
      "Strong CI/CD automation within AWS CodePipeline",
    ],
    tradeoffs: [
      "Best value when deep in AWS — limited value for non-AWS stacks",
      "Primarily a coding assistant — limited orchestration/autopilot",
      "No visual workflow canvas or playbook system",
      "Community and third-party integrations smaller than GitHub Copilot",
      "Less capable outside AWS contexts",
    ],
    bestFor: "Teams running on AWS infrastructure who want AI assistance that understands their cloud stack natively — especially for security, compliance, and infrastructure-as-code work.",
  },
  {
    id: "coderabbit",
    shortName: "CodeRabbit",
    name: "CodeRabbit AI",
    maker: "CodeRabbit",
    emoji: "🐰",
    category: "AI Code Review",
    categoryColor: "bg-pink-100 text-pink-700",
    url: "https://coderabbit.ai",
    oneLiner: "Automated AI PR reviewer that installs as a GitHub/GitLab app and posts detailed, contextual line-by-line review comments.",
    description: "CodeRabbit is a focused, well-executed AI code review product. Install it as a GitHub or GitLab app, and it automatically reviews every PR — posting line-by-line comments, a summary, and a walkthrough of the changes. It supports custom review instructions, learning from dismissals, and integrates with Linear and Jira to read ticket context. The product is beloved for how little setup it requires — install in 60 seconds and it starts reviewing immediately. It has a generous free tier for open source projects.",
    strengths: [
      "Zero-setup — installs as a GitHub app, reviews immediately",
      "Excellent line-by-line review comments with context",
      "Learns from feedback — improves over time per repo",
      "Generous free tier for open source",
      "Supports GitHub, GitLab, Azure DevOps, Bitbucket",
      "Custom review instructions via `.coderabbit.yaml`",
    ],
    tradeoffs: [
      "Review only — no autonomous fix capability or autopilot loop",
      "No human-in-the-loop gates or approval workflows",
      "No visual canvas or workflow customisation beyond config YAML",
      "Does not create fix issues or trigger downstream automation",
      "No incident response, issue triage, or CI failure features",
    ],
    bestFor: "Teams that want instant, zero-config AI code review on every PR without building any automation. Best as a safety net alongside a human review process — not as a replacement for a full automation pipeline.",
  },
  {
    id: "runtm",
    shortName: "Runtm",
    name: "Runtm",
    maker: "Runtm",
    emoji: "📦",
    category: "Sandbox Runtime",
    categoryColor: "bg-emerald-100 text-emerald-700",
    url: "https://runtm.com",
    oneLiner: "Open-source sandboxes where coding agents build and deploy. Spin up isolated environments for Claude Code, Cursor, Codex, and others — with live HTTPS URLs, logs, and previews.",
    description: "Runtm is a sandbox aggregation layer for coding agents — an abstraction that sits above cloud execution backends (E2B, Modal, AWS EC2, Daytona, Vercel) and coding agents (Claude Code, OpenAI Codex, Cursor, Devin, Gemini, GitHub Copilot) alike. Rather than committing to a single cloud VM or container service, you connect Runtm once and get a unified API and dashboard across all of them. Agents run in isolated sandboxes, deploy to live HTTPS URLs, and emit session logs and cost metrics — regardless of which backend is powering the box. Where Conduct is the orchestration layer that decides what an agent should do and when to trigger it, Runtm is the aggregated runtime layer where execution happens. The integration story is multiplicative: adding a single Runtm adapter to Conduct's sandbox dispatch unlocks every backend Runtm already supports — E2B, Modal, Daytona, EC2, Vercel — without writing a separate adapter for each.",
    strengths: [
      "Sandbox aggregator — single integration covers E2B, Modal, AWS EC2, Daytona, and Vercel backends",
      "Agent-agnostic — Claude Code, Codex, Cursor, Devin, Gemini CLI, GitHub Copilot all supported",
      "Live HTTPS deploy URLs out of the box — test and share instantly",
      "Real-time session logs and observability built-in across all backends",
      "Cost tracking and approval gates per agent or team",
      "Multi-team deployment — each department gets a dedicated named agent",
      "Open source (AGPL server, Apache CLI, MIT templates) — self-hostable",
      "Auto-stopping infrastructure — machines spin down when idle",
    ],
    tradeoffs: [
      "Runtime layer only — no workflow orchestration, playbooks, or trigger logic",
      "No event-driven automation — sessions are user-initiated, not triggered by GitHub labels or webhooks",
      "No pre-built playbooks or agent logic marketplace",
      "No multi-block DAG orchestration, logic gates, or approval flow builder",
      "No Slack-native output or incident response features",
      "Primarily a CLI and browser product — no visual workflow canvas",
    ],
    bestFor: "Teams that want to give coding agents (Claude Code, Cursor, Codex) a safe, isolated place to run with live deploy URLs and observability — without worrying about infrastructure. Best paired with an orchestration layer like Conduct that decides what the agent should build and when to trigger it.",
  },
  {
    id: "xhawk",
    shortName: "xHawk",
    name: "xHawk AI",
    maker: "xHawk",
    emoji: "🦅",
    category: "Autonomous SDLC",
    categoryColor: "bg-red-100 text-red-700",
    url: "https://xhawk.ai",
    oneLiner: "Autonomous AI agents for the full software development lifecycle — issue to deployment — targeted at enterprise SDLC automation.",
    description: "xHawk focuses on end-to-end SDLC automation: from issue creation through code generation, testing, code review, and deployment. It targets enterprise teams that want to automate the full software delivery pipeline with AI. xHawk is more opinionated about the SDLC process and less flexible for general-purpose agent workflows. Based on public information, it is primarily configured via code/API rather than a visual interface, and is positioned at larger engineering organisations.",
    strengths: [
      "End-to-end SDLC coverage — issue through deploy in one platform",
      "Enterprise-grade — built for larger teams and compliance requirements",
      "Strong focus on software delivery metrics and pipeline automation",
      "Deep integration with enterprise toolchains (Jira, Confluence, etc.)",
    ],
    tradeoffs: [
      "SDLC-only scope — not designed for general-purpose agent workflows",
      "Code-driven configuration — no visual workflow canvas",
      "Less flexible for teams outside the standard enterprise SDLC pattern",
      "Smaller public community and fewer public resources",
      "Pricing and availability less transparent than open-source alternatives",
    ],
    bestFor: "Larger enterprise engineering organisations that want automated end-to-end SDLC pipelines with enterprise toolchain integrations and are comfortable with code-driven configuration over a visual interface.",
  },
]

export const FEATURE_GROUPS = [
  {
    label: "Workflow & Automation",
    features: [
      {
        name: "Visual workflow canvas",
        note: "Build and edit agent logic visually",
        values: { conduct: "✅", copilot: "❌", devin: "❌", linearb: "❌", bito: "❌", amazonq: "❌", coderabbit: "❌", xhawk: "❌", runtm: "❌" },
      },
      {
        name: "Pre-built playbooks / agents",
        note: "Install and run without building from scratch",
        values: { conduct: "✅", copilot: "🟡", devin: "❌", linearb: "🟡", bito: "❌", amazonq: "🟡", coderabbit: "❌", xhawk: "🟡", runtm: "❌" },
      },
      {
        name: "Custom workflow builder",
        note: "Define your own agent logic",
        values: { conduct: "✅", copilot: "🟡", devin: "❌", linearb: "🟡", bito: "❌", amazonq: "❌", coderabbit: "🟡 YAML", xhawk: "✅", runtm: "❌" },
      },
      {
        name: "Human-in-the-loop approval gates",
        note: "Pause for human review before proceeding",
        values: { conduct: "✅", copilot: "❌", devin: "❌", linearb: "🟡", bito: "❌", amazonq: "❌", coderabbit: "❌", xhawk: "🟡", runtm: "✅" },
      },
      {
        name: "Copilot mode (suggestions)",
        note: "AI suggests, human decides",
        values: { conduct: "✅", copilot: "✅", devin: "🟡", linearb: "✅", bito: "✅", amazonq: "✅", coderabbit: "✅", xhawk: "🟡", runtm: "❌" },
      },
      {
        name: "Autopilot mode (autonomous execution)",
        note: "AI acts end-to-end without prompting",
        values: { conduct: "✅", copilot: "🟡", devin: "✅", linearb: "🟡", bito: "❌", amazonq: "🟡", coderabbit: "❌", xhawk: "✅", runtm: "✅" },
      },
    ],
  },
  {
    label: "Code Review",
    features: [
      {
        name: "Automated PR review",
        note: "Reviews pull requests and posts comments",
        values: { conduct: "✅", copilot: "🟡", devin: "🟡", linearb: "✅", bito: "✅", amazonq: "🟡", coderabbit: "✅", xhawk: "✅", runtm: "❌" },
      },
      {
        name: "Line-by-line inline comments",
        values: { conduct: "✅", copilot: "✅", devin: "❌", linearb: "✅", bito: "✅", amazonq: "🟡", coderabbit: "✅", xhawk: "🟡", runtm: "❌" },
      },
      {
        name: "Deep codebase context (full repo awareness)",
        values: { conduct: "🟡", copilot: "✅", devin: "✅", linearb: "🟡", bito: "✅", amazonq: "✅", coderabbit: "🟡", xhawk: "🟡", runtm: "🟡" },
      },
      {
        name: "Security / vulnerability scanning",
        note: "OWASP Top 10, secret detection, insecure deps",
        values: { conduct: "✅", copilot: "🟡", devin: "🟡", linearb: "❌", bito: "✅", amazonq: "✅", coderabbit: "✅", xhawk: "🟡", runtm: "❌" },
      },
    ],
  },
  {
    label: "Autonomous Task Execution",
    features: [
      {
        name: "Issue → PR autopilot",
        note: "Label a GitHub issue, get a PR",
        values: { conduct: "✅", copilot: "🟡", devin: "✅", linearb: "❌", bito: "❌", amazonq: "🟡", coderabbit: "❌", xhawk: "✅", runtm: "❌" },
      },
      {
        name: "Autonomous fix loop",
        note: "Review finds issues → creates fix issue → autopilot re-picks up → new PR → re-review",
        values: { conduct: "✅", copilot: "❌", devin: "❌", linearb: "❌", bito: "❌", amazonq: "❌", coderabbit: "❌", xhawk: "🟡", runtm: "❌" },
      },
      {
        name: "CI failure diagnosis",
        values: { conduct: "✅", copilot: "🟡", devin: "🟡", linearb: "🟡", bito: "❌", amazonq: "🟡", coderabbit: "❌", xhawk: "✅", runtm: "❌" },
      },
      {
        name: "Incident response automation",
        values: { conduct: "✅", copilot: "❌", devin: "❌", linearb: "❌", bito: "❌", amazonq: "🟡", coderabbit: "❌", xhawk: "🟡", runtm: "❌" },
      },
      {
        name: "Automated dependency updates",
        values: { conduct: "✅", copilot: "❌", devin: "🟡", linearb: "❌", bito: "❌", amazonq: "❌", coderabbit: "❌", xhawk: "🟡", runtm: "❌" },
      },
      {
        name: "Release notes generation",
        values: { conduct: "✅", copilot: "❌", devin: "❌", linearb: "🟡", bito: "❌", amazonq: "❌", coderabbit: "❌", xhawk: "❌", runtm: "❌" },
      },
      {
        name: "Issue triage & labeling",
        values: { conduct: "✅", copilot: "🟡", devin: "🟡", linearb: "🟡", bito: "❌", amazonq: "❌", coderabbit: "❌", xhawk: "✅", runtm: "❌" },
      },
    ],
  },
  {
    label: "Observability & Trust",
    features: [
      {
        name: "Full run audit trail",
        note: "Every action logged and replayable",
        values: { conduct: "✅", copilot: "❌", devin: "🟡", linearb: "✅", bito: "❌", amazonq: "🟡", coderabbit: "❌", xhawk: "🟡", runtm: "✅" },
      },
      {
        name: "Per-run cost transparency",
        values: { conduct: "✅", copilot: "❌", devin: "❌", linearb: "❌", bito: "❌", amazonq: "❌", coderabbit: "❌", xhawk: "❌", runtm: "✅" },
      },
      {
        name: "Multi-model per block",
        note: "Use different LLMs for different steps",
        values: { conduct: "✅", copilot: "🟡", devin: "❌", linearb: "❌", bito: "❌", amazonq: "❌", coderabbit: "❌", xhawk: "❌", runtm: "❌" },
      },
      {
        name: "Engineering metrics dashboard",
        note: "DORA, cycle time, deployment freq",
        values: { conduct: "❌", copilot: "❌", devin: "❌", linearb: "✅", bito: "❌", amazonq: "🟡", coderabbit: "❌", xhawk: "🟡", runtm: "❌" },
      },
    ],
  },
  {
    label: "Integration & Access",
    features: [
      {
        name: "GitHub integration",
        values: { conduct: "✅", copilot: "✅", devin: "✅", linearb: "✅", bito: "✅", amazonq: "✅", coderabbit: "✅", xhawk: "✅", runtm: "✅" },
      },
      {
        name: "Slack-native output",
        values: { conduct: "✅", copilot: "❌", devin: "❌", linearb: "✅", bito: "❌", amazonq: "❌", coderabbit: "❌", xhawk: "🟡", runtm: "✅" },
      },
      {
        name: "IDE extension",
        values: { conduct: "❌", copilot: "✅", devin: "✅", linearb: "❌", bito: "✅", amazonq: "✅", coderabbit: "❌", xhawk: "❌", runtm: "❌" },
      },
      {
        name: "CLI / API",
        values: { conduct: "✅", copilot: "🟡", devin: "✅", linearb: "✅", bito: "✅", amazonq: "✅", coderabbit: "✅", xhawk: "✅", runtm: "✅" },
      },
      {
        name: "Open source",
        values: { conduct: "✅ MIT", copilot: "❌", devin: "❌", linearb: "❌", bito: "❌", amazonq: "❌", coderabbit: "❌", xhawk: "❌", runtm: "✅ AGPL/Apache/MIT" },
      },
      {
        name: "Free tier",
        values: { conduct: "✅", copilot: "✅", devin: "❌", linearb: "🟡", bito: "✅", amazonq: "✅", coderabbit: "✅", xhawk: "❌", runtm: "✅" },
      },
      {
        name: "No custom infrastructure required",
        values: { conduct: "✅", copilot: "✅", devin: "✅", linearb: "✅", bito: "✅", amazonq: "✅", coderabbit: "✅", xhawk: "🟡", runtm: "✅" },
      },
      {
        name: "Isolated sandbox execution",
        note: "Agent execution runs in a sandbox-backed or configured runtime",
        values: { conduct: "✅ Modal/SSH", copilot: "❌", devin: "✅", linearb: "❌", bito: "❌", amazonq: "❌", coderabbit: "❌", xhawk: "🟡", runtm: "✅" },
      },
      {
        name: "Live deploy URL from sandbox",
        note: "Agent builds and deploys to a shareable HTTPS endpoint",
        values: { conduct: "❌", copilot: "❌", devin: "🟡", linearb: "❌", bito: "❌", amazonq: "❌", coderabbit: "❌", xhawk: "❌", runtm: "✅" },
      },
    ],
  },
]

export const DECISION_GUIDE = [
  {
    icon: "✍️",
    situation: "I want the best AI autocomplete and code chat in my IDE",
    detail: "This is about productivity while writing code. You want fast, accurate suggestions, multi-file edits, and a chat interface that understands your codebase.",
    picks: [
      { name: "GitHub Copilot", highlight: true },
      { name: "Amazon Q Developer", highlight: false },
      { name: "Bito AI", highlight: false },
    ],
  },
  {
    icon: "🔍",
    situation: "I want automated PR review on every pull request with zero setup",
    detail: "You want an AI reviewer watching every PR. Install it and forget it — no workflow to configure, no canvas to build.",
    picks: [
      { name: "CodeRabbit AI", highlight: true },
      { name: "Bito AI", highlight: false },
      { name: "Conduct AI", highlight: false },
    ],
  },
  {
    icon: "🤖",
    situation: "I want to hand off a complex task and let AI do it fully autonomously",
    detail: "You have a well-scoped ticket and want an AI to handle the entire implementation end-to-end — planning, coding, debugging, and opening a PR.",
    picks: [
      { name: "Devin", highlight: true },
      { name: "Conduct AI (Autopilot)", highlight: false },
      { name: "GitHub Copilot (agentic)", highlight: false },
    ],
  },
  {
    icon: "👁️",
    situation: "I want automation but with human control over what ships",
    detail: "Full autonomy makes you nervous. You want agents doing the work, but a human checkpoint before anything lands in main.",
    picks: [
      { name: "Conduct AI", highlight: true },
      { name: "LinearB (gitStream)", highlight: false },
    ],
  },
  {
    icon: "🔄",
    situation: "I want PR review → auto-fix → re-review to run without me touching it",
    detail: "The full autonomous loop: PR opened, reviewed, critical issues create a fix issue, Autopilot fixes it, new PR opened, reviewed again — hands-free.",
    picks: [
      { name: "Conduct AI", highlight: true },
    ],
  },
  {
    icon: "📊",
    situation: "I'm an engineering manager who wants team performance metrics + PR automation",
    detail: "DORA metrics, cycle time, deployment frequency, and policy-based PR routing all in one place.",
    picks: [
      { name: "LinearB", highlight: true },
      { name: "Conduct AI", highlight: false },
    ],
  },
  {
    icon: "☁️",
    situation: "My stack is heavily AWS and I want AI that understands my infrastructure",
    detail: "CloudFormation, CDK, Lambda, CodePipeline — you need an AI that speaks AWS natively and can handle security scanning and language upgrades.",
    picks: [
      { name: "Amazon Q Developer", highlight: true },
      { name: "GitHub Copilot", highlight: false },
    ],
  },
  {
    icon: "🏢",
    situation: "I'm at a large enterprise and need end-to-end SDLC automation",
    detail: "Enterprise toolchains (Jira, Confluence, ServiceNow), compliance requirements, and a full pipeline from issue creation through deployment.",
    picks: [
      { name: "xHawk AI", highlight: true },
      { name: "Conduct AI", highlight: false },
      { name: "LinearB", highlight: false },
    ],
  },
  {
    icon: "📦",
    situation: "I want a safe sandbox where my coding agent can build and deploy to a live URL",
    detail: "You want to point Claude Code, Cursor, or Codex at an isolated environment — full permissions inside the box, zero risk outside — and get a live HTTPS endpoint when the agent is done.",
    picks: [
      { name: "Runtm", highlight: true },
      { name: "Devin", highlight: false },
    ],
  },
  {
    icon: "🔀",
    situation: "I want event-driven automation (GitHub → agent → PR) with a safe sandbox backend",
    detail: "GitHub labels an issue → Conduct triggers a playbook → the agent runs in the configured workspace runtime → PR opened. Orchestration and runtime, working together.",
    picks: [
      { name: "Conduct AI", highlight: true },
      { name: "Runtm", highlight: false },
    ],
  },
  {
    icon: "🔓",
    situation: "I want open-source, no vendor lock-in, config-as-code",
    detail: "Workflows as YAML in your repo, MIT licensed, self-hostable direction, and the ability to audit or modify the logic.",
    picks: [
      { name: "Conduct AI", highlight: true },
    ],
  },
]
